version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
